name: Deploy to .80 on push

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy LuftDocs
        shell: pwsh
        run: |
          & "C:\ProjetosPython\LuftDocs\deploy.ps1" `
            -AppDir "C:\ProjetosPython\LuftDocs\LuftDocs_Web" `
            -ServiceName "LuftDocs" `
            -HealthUrl "http://127.0.0.1:9001/health"
